"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, Check, Copy, HeartPulse, Link2, RefreshCw, Scale, ShieldCheck, Trash2, Watch } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Connection = { last_successful_sync?: string | null; last_error?: string | null } | null;
type Metric = { metric_type: string; value: number; unit: string; recorded_at: string };
type Workout = { workout_type: string; started_at: string; duration_seconds: number | null; energy_kcal: number | null };
type Sleep = { sleep_date: string; asleep_seconds: number | null; deep_seconds: number | null; rem_seconds: number | null; core_seconds: number | null };

const fmtDuration = (seconds: number | null | undefined) => seconds == null ? "—" : `${Math.floor(seconds / 3600)}h ${Math.round((seconds % 3600) / 60)}m`;

export function ConnectedHealthCard({ isLoggedIn, compact = false }: { isLoggedIn: boolean; compact?: boolean }) {
  const [connection, setConnection] = useState<Connection>(null); const [token, setToken] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [weight, setWeight] = useState("");
  const [metrics, setMetrics] = useState<Metric[]>([]); const [workouts, setWorkouts] = useState<Workout[]>([]); const [sleep, setSleep] = useState<Sleep[]>([]);
  const load = async () => { if (!isLoggedIn) return; const res = await fetch("/api/health/connection"); if (res.ok) setConnection((await res.json()).connection); const db = createClient(); const [m, w, s] = await Promise.all([db.from("health_metric_samples").select("metric_type,value,unit,recorded_at").order("recorded_at", { ascending: false }).limit(90), db.from("workouts").select("workout_type,started_at,duration_seconds,energy_kcal").order("started_at", { ascending: false }).limit(20), db.from("sleep_sessions").select("sleep_date,asleep_seconds,deep_seconds,rem_seconds,core_seconds").order("sleep_date", { ascending: false }).limit(14)]); setMetrics((m.data ?? []) as Metric[]); setWorkouts((w.data ?? []) as Workout[]); setSleep((s.data ?? []) as Sleep[]); };
  useEffect(() => { void load(); }, [isLoggedIn]);
  const latestWeight = metrics.find((m) => m.metric_type === "weight"); const latestRhr = metrics.find((m) => m.metric_type === "resting_heart_rate"); const latestHrv = metrics.find((m) => m.metric_type === "hrv"); const lastNight = sleep[0];
  const weeklyWorkouts = workouts.filter((w) => Date.now() - new Date(w.started_at).getTime() < 7 * 86400000); const weeklyMinutes = Math.round(weeklyWorkouts.reduce((sum, w) => sum + (w.duration_seconds ?? 0), 0) / 60);
  const trend = useMemo(() => metrics.filter((m) => m.metric_type === "weight").slice(0, 30).reverse(), [metrics]);
  const generate = async () => { setBusy(true); setMessage(""); const res = await fetch("/api/health/connection", { method: "POST" }); const data = await res.json(); setBusy(false); if (!res.ok) { setMessage(data.error ?? "Could not create token"); return; } setToken(data.token); setMessage("Token created. It is shown once—copy it now."); await load(); };
  const revoke = async () => { setBusy(true); await fetch("/api/health/connection", { method: "DELETE" }); setBusy(false); setToken(""); setConnection(null); setMessage("Connection revoked."); };
  const saveWeight = async () => { const res = await fetch("/api/health/weight", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ weightKg: Number(weight) }) }); const data = await res.json(); setMessage(res.ok ? "Weight saved. Nutrition goals were not changed." : data.error); if (res.ok) { setWeight(""); await load(); } };
  if (!isLoggedIn) return <div className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-muted" /><p className="text-xs font-bold text-foreground">Connected Health</p></div><p className="mt-1 text-[11px] text-muted">Sign in to connect Apple Health securely. Guest meal logging stays available.</p></div>;
  return <div className="space-y-3">
    {!compact && <div><h3 className="text-sm font-extrabold text-foreground">Connected Health</h3><p className="text-[11px] text-muted mt-0.5">Apple Health → Health Auto Export → SnackOverflow</p></div>}
    {!connection ? <div className="rounded-2xl border border-accent/20 bg-accent-light/30 p-4"><div className="flex items-start gap-3"><Link2 className="h-4 w-4 text-accent-dim mt-0.5" /><div className="flex-1"><p className="text-xs font-bold text-foreground">Connect Apple Health</p><p className="text-[11px] text-muted mt-1">Health Auto Export is the iPhone bridge. Generate a private endpoint token, then configure two daily exports.</p><button onClick={generate} disabled={busy} className="mt-3 rounded-lg bg-foreground px-3 py-2 text-[11px] font-bold text-white disabled:opacity-50">{busy ? "Creating…" : "Generate connection token"}</button></div></div></div> : <div className="rounded-2xl border border-border bg-card p-4 space-y-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Watch className="h-4 w-4 text-green-600" /><div><p className="text-xs font-bold text-foreground">Apple Health connected</p><p className="text-[10px] text-muted">{connection.last_successful_sync ? `Last sync ${new Date(connection.last_successful_sync).toLocaleString("en-IN")}` : "Waiting for first sync"}</p></div></div><button onClick={revoke} className="text-muted hover:text-red-600" title="Revoke token"><Trash2 className="h-3.5 w-3.5" /></button></div>
      {token && <div className="rounded-xl bg-background border border-border p-3"><p className="text-[10px] font-bold text-muted mb-1">Copy this token into your exporter or Shortcut</p><div className="flex gap-2"><code className="min-w-0 flex-1 break-all text-[10px] text-foreground">{token}</code><button onClick={() => navigator.clipboard?.writeText(token)} className="shrink-0 rounded-md border border-border p-1.5" title="Copy token"><Copy className="h-3 w-3" /></button></div><p className="mt-2 text-[10px] text-muted">Health Auto Export endpoint: <code>/api/health/ingest/apple-health</code></p><p className="mt-1 text-[10px] text-muted">Shortcut endpoint: <code>/api/health/ingest/shortcut</code></p></div>}
      {connection.last_error && <p className="text-[10px] text-red-600">Last sync error: {connection.last_error}</p>}
    </div>}
    <HealthSetupGuide />
    <div className="grid grid-cols-2 gap-2"><Mini icon={HeartPulse} label="Sleep" value={fmtDuration(lastNight?.asleep_seconds)} /><Mini icon={Activity} label="7-day activity" value={`${weeklyWorkouts.length} · ${weeklyMinutes}m`} /><Mini icon={Scale} label="Latest weight" value={latestWeight ? `${latestWeight.value.toFixed(1)} kg` : "—"} /><Mini icon={HeartPulse} label="RHR / HRV" value={`${latestRhr?.value ?? "—"} / ${latestHrv?.value ?? "—"}`} /></div>
    {lastNight && <div className="rounded-xl border border-border bg-card p-3"><p className="text-[11px] font-bold text-foreground">Recovery · {lastNight.sleep_date}</p><div className="mt-2 grid grid-cols-3 text-center"><MiniText label="Core" value={fmtDuration(lastNight.core_seconds)} /><MiniText label="Deep" value={fmtDuration(lastNight.deep_seconds)} /><MiniText label="REM" value={fmtDuration(lastNight.rem_seconds)} /></div></div>}
    <div className="rounded-xl border border-border bg-card p-3"><div className="flex items-center justify-between"><p className="text-[11px] font-bold text-foreground">Manual weight</p><p className="text-[10px] text-muted">{trend.length ? `${trend.length} measurements` : "No measurements"}</p></div><div className="mt-2 flex gap-2"><input value={weight} onChange={(e) => setWeight(e.target.value)} type="number" min="20" max="500" step="0.1" placeholder="kg" className="min-w-0 flex-1 rounded-lg border border-border bg-background px-2.5 py-2 text-xs" /><button onClick={saveWeight} disabled={!weight} className="rounded-lg bg-foreground px-3 py-2 text-[11px] font-bold text-white disabled:opacity-40">Save</button></div><p className="mt-2 text-[10px] text-muted">Adds a measurement and updates profile weight. It does not recalculate nutrition goals.</p></div>
    {message && <p className="text-[10px] text-accent-dim flex items-center gap-1"><Check className="h-3 w-3" />{message}</p>}<button onClick={() => void load()} className="flex items-center gap-1 text-[10px] font-semibold text-muted hover:text-foreground"><RefreshCw className="h-3 w-3" />Refresh health data</button>
  </div>;
}

function Mini({ icon: Icon, label, value }: { icon: typeof Activity; label: string; value: string }) { return <div className="rounded-xl border border-border bg-card p-3"><Icon className="h-3.5 w-3.5 text-accent" /><p className="mt-1 text-[10px] text-muted">{label}</p><p className="text-sm font-extrabold text-foreground">{value}</p></div>; }
function MiniText({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] text-muted">{label}</p><p className="text-[11px] font-bold text-foreground">{value}</p></div>; }

function HealthSetupGuide() {
  return <details open className="rounded-2xl border border-border bg-card p-4"><summary className="cursor-pointer text-xs font-extrabold text-foreground">How to connect Apple Health</summary><div className="mt-3 space-y-3 text-[11px] text-muted"><p><strong className="text-foreground">What this does:</strong> Apple Health collects data from your Apple Watch, JEFIT, and smart scale. You can use Health Auto Export Premium for automatic REST API syncing, or use the free Shortcut method below.</p><ol className="list-decimal pl-4 space-y-2"><li><strong className="text-foreground">Create your SnackOverflow connection.</strong> Tap <em>Generate connection token</em> above. Copy the token and keep it private. If you lose it, revoke the connection and generate a new one.</li><li><strong className="text-foreground">Choose an exporter.</strong> For automatic syncing, install <em>Health Auto Export - JSON+CSV</em>, allow Apple Health access, and configure its REST API automation. For a free option, use the Shortcut method below.</li><li><strong className="text-foreground">Configure automatic export.</strong> In Health Auto Export, open <em>Automated Exports</em>, choose <em>REST API</em>, use the Health Auto Export endpoint above, and add Bearer authorization with your SnackOverflow token. Select JSON/v2 data and include workouts and health metrics.</li><li><strong className="text-foreground">Backfill and schedule.</strong> Run the first export for the last 30 days. Then schedule a daily rolling 3-day export so edits and delayed Apple Health data are picked up.</li></ol><div className="rounded-xl bg-accent-light/40 border border-accent/10 p-3"><p className="font-bold text-foreground">Free Shortcut method</p><p className="mt-1">Download the Shortcut below. After importing it, edit the POST action and replace the URL and bearer-token placeholders with the values shown above. Then export a JSON file from Health Auto Export, share the file to the Shortcut, and run it. The Shortcut posts the file to SnackOverflow without Premium.</p><a href="/shortcuts/snackoverflow-health-sync.shortcut" download className="mt-2 inline-flex rounded-lg bg-foreground px-3 py-2 text-[10px] font-bold text-white">Download Shortcut</a><p className="mt-2 text-[10px]">Shortcut endpoint: <code>/api/health/ingest/shortcut</code></p></div><div className="rounded-xl bg-background border border-border p-3"><p className="font-bold text-foreground">Where your data goes</p><p className="mt-1">Apple Watch / JEFIT / scale → Apple Health → exporter or Shortcut → SnackOverflow → your private Supabase data.</p></div><p className="text-[10px]">Automatic iPhone syncing can be delayed by iOS. With the free method, run the Shortcut after exporting a JSON file. Return here and tap Refresh health data after uploading.</p></div></details>;
}
