"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, Check, ChevronDown, ChevronUp, Copy, ExternalLink, FileUp, Flame, HeartPulse, Link2, MapPin, RefreshCw, Scale, ShieldCheck, Timer, Trash2, Watch } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Connection = { last_successful_sync?: string | null; last_error?: string | null } | null;
type Metric = { metric_type: string; value: number; unit: string; recorded_at: string; provider?: string };
type Workout = { workout_type: string; started_at: string; ended_at: string; duration_seconds: number | null; energy_kcal: number | null; distance_km: number | null; heart_rate_avg_bpm: number | null; heart_rate_min_bpm?: number | null; heart_rate_max_bpm?: number | null; provider?: string };
type Sleep = { sleep_date: string; started_at: string; ended_at: string; asleep_seconds: number | null; in_bed_seconds?: number | null; deep_seconds: number | null; rem_seconds: number | null; core_seconds: number | null; provider?: string };
type SyncMethod = "premium" | "basic";

const fmtDuration = (seconds: number | null | undefined) => seconds == null ? "—" : `${Math.floor(seconds / 3600)}h ${Math.round((seconds % 3600) / 60)}m`;
const fmtDate = (iso: string) => new Date(iso).toLocaleDateString("en-IN", { day: "numeric", month: "short" });
const effectiveSleepSeconds = (session: Sleep | undefined) => {
  if (!session) return null;
  if (session.asleep_seconds != null && session.asleep_seconds > 0) return session.asleep_seconds;
  const stages = [session.core_seconds, session.deep_seconds, session.rem_seconds].filter((value): value is number => value != null && value > 0).reduce((sum, value) => sum + value, 0);
  if (stages > 0) return stages;
  const elapsed = Math.round((new Date(session.ended_at).getTime() - new Date(session.started_at).getTime()) / 1000);
  return elapsed > 0 ? elapsed : null;
};

export function ConnectedHealthCard({ isLoggedIn, compact = false }: { isLoggedIn: boolean; compact?: boolean }) {
  const [connection, setConnection] = useState<Connection>(null);
  const [token, setToken] = useState("");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [weight, setWeight] = useState("");
  const [method, setMethod] = useState<SyncMethod>("premium");
  const uploadRef = useRef<HTMLInputElement>(null);
  const [metrics, setMetrics] = useState<Metric[]>([]);
  const [workouts, setWorkouts] = useState<Workout[]>([]);
  const [sleep, setSleep] = useState<Sleep[]>([]);

  const load = async () => {
    if (!isLoggedIn) return;
    const res = await fetch("/api/health/connection");
    if (res.ok) setConnection((await res.json()).connection);
    const db = createClient();
    const [m, w, s] = await Promise.all([
      db.from("health_metric_samples").select("metric_type,value,unit,recorded_at,provider").order("recorded_at", { ascending: false }).limit(180),
      db.from("workouts").select("workout_type,started_at,ended_at,duration_seconds,energy_kcal,distance_km,heart_rate_avg_bpm,heart_rate_min_bpm,heart_rate_max_bpm,provider").order("started_at", { ascending: false }).limit(20),
      db.from("sleep_sessions").select("sleep_date,started_at,ended_at,asleep_seconds,in_bed_seconds,deep_seconds,rem_seconds,core_seconds,provider").order("sleep_date", { ascending: false }).limit(14),
    ]);
    setMetrics((m.data ?? []) as Metric[]); setWorkouts((w.data ?? []) as Workout[]); setSleep((s.data ?? []) as Sleep[]);
  };

  useEffect(() => { void load(); }, [isLoggedIn]);

  const latest = (type: string) => metrics.find((item) => item.metric_type === type);
  const latestWeight = latest("weight"); const latestRhr = latest("resting_heart_rate"); const latestHrv = latest("hrv"); const latestSteps = latest("steps"); const lastNight = sleep[0]; const latestWorkout = workouts[0];
  const lastNightSleepSeconds = effectiveSleepSeconds(lastNight);
  const weeklyWorkouts = workouts.filter((w) => { const age = Date.now() - new Date(w.started_at).getTime(); return age >= 0 && age < 7 * 86400000; });
  const weeklyMinutes = Math.round(weeklyWorkouts.reduce((sum, w) => sum + (w.duration_seconds ?? 0), 0) / 60);
  const weeklyEnergy = Math.round(weeklyWorkouts.reduce((sum, w) => sum + (w.energy_kcal ?? 0), 0));
  const weightTrend = useMemo(() => metrics.filter((m) => m.metric_type === "weight").slice(0, 30).reverse(), [metrics]);

  const generate = async () => { setBusy(true); setMessage(""); const res = await fetch("/api/health/connection", { method: "POST" }); const data = await res.json(); setBusy(false); if (!res.ok) { setMessage(data.error ?? "Could not create token"); return; } setToken(data.token); setMessage("Token created. Copy it now; it is shown once."); await load(); };
  const revoke = async () => { setBusy(true); await fetch("/api/health/connection", { method: "DELETE" }); setBusy(false); setToken(""); setConnection(null); setMessage("Connection revoked."); };
  const saveWeight = async () => { const res = await fetch("/api/health/weight", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ weightKg: Number(weight) }) }); const data = await res.json(); setMessage(res.ok ? "Weight saved. Nutrition goals were not changed." : data.error); if (res.ok) { setWeight(""); await load(); } };
  const uploadExport = async (file: File) => { setBusy(true); setMessage(""); const body = await file.text(); const res = await fetch("/api/health/import", { method: "POST", headers: { "Content-Type": "application/json" }, body }); const data = await res.json(); setBusy(false); setMessage(res.ok ? `Imported ${data.imported?.sleep ?? 0} sleep sessions, ${data.imported?.workouts ?? 0} workouts, and ${data.imported?.metrics ?? 0} metrics.` : data.error ?? "Import failed"); if (res.ok) await load(); };

  if (!isLoggedIn) return <div className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-muted" /><p className="text-xs font-bold text-foreground">Connected Health</p></div><p className="mt-1 text-[11px] text-muted">Sign in to connect Apple Health securely. Guest meal logging stays available.</p></div>;

  return <div className="space-y-3">
    {!compact && <div><h3 className="text-sm font-extrabold text-foreground">Connected Health</h3><p className="text-[11px] text-muted mt-0.5">Your health data, all in one place</p></div>}
    {!compact && <details className="rounded-2xl border border-border bg-card"><summary className="cursor-pointer list-none p-4 text-xs font-extrabold text-foreground">Sync setup <span className="ml-1 text-[10px] font-medium text-muted">Automatic or file upload</span></summary><div className="px-4 pb-4"><SyncMethodChooser method={method} setMethod={setMethod} connected={Boolean(connection)} token={token} generate={generate} busy={busy} uploadRef={uploadRef} uploadExport={uploadExport} /></div></details>}
    {connection ? <div className="rounded-2xl border border-border bg-card p-4 space-y-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Watch className="h-4 w-4 text-green-600" /><div><p className="text-xs font-bold text-foreground">Connected health data</p><p className="text-[10px] text-muted">{connection.last_successful_sync ? `Last sync ${new Date(connection.last_successful_sync).toLocaleString("en-IN")}` : "Waiting for first sync"}</p></div></div><button onClick={revoke} className="text-muted hover:text-red-600" title="Revoke token"><Trash2 className="h-3.5 w-3.5" /></button></div>{token && <div className="rounded-xl bg-background border border-border p-3"><p className="text-[10px] font-bold text-muted mb-1">Bearer token</p><div className="flex gap-2"><code className="min-w-0 flex-1 break-all text-[10px] text-foreground">{token}</code><button onClick={() => navigator.clipboard?.writeText(token)} className="shrink-0 rounded-md border border-border p-1.5" title="Copy token"><Copy className="h-3 w-3" /></button></div></div>}{connection.last_error && <p className="text-[10px] text-red-600">Last import error: {connection.last_error}</p>}</div> : <div className="rounded-2xl border border-accent/20 bg-accent-light/30 p-4"><div className="flex items-start gap-3"><Link2 className="h-4 w-4 text-accent-dim mt-0.5" /><div><p className="text-xs font-bold text-foreground">Connect health data</p><p className="text-[11px] text-muted mt-1">Create one secure connection, then choose Automatic or Free upload above.</p><button onClick={generate} disabled={busy} className="mt-3 rounded-lg bg-foreground px-3 py-2 text-[11px] font-bold text-white disabled:opacity-50">{busy ? "Creating…" : "Create connection"}</button></div></div></div>}
    <div className="rounded-2xl border border-accent/20 bg-gradient-to-br from-accent-light/70 via-card to-card p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-accent-dim">Today’s health</p><p className="mt-1 text-lg font-extrabold text-foreground">{lastNightSleepSeconds ? "Recovery looks promising" : metrics.length || lastNight ? "Health picture is taking shape" : "Build your health picture"}</p></div><div className="flex h-14 w-14 items-center justify-center rounded-full border-4 border-accent/30 text-center"><span className="text-xs font-extrabold text-accent-dim">{lastNightSleepSeconds ? `${Math.min(100, Math.round((lastNightSleepSeconds / 28800) * 100))}%` : "—"}</span></div></div><p className="mt-2 text-[11px] text-muted">{lastNightSleepSeconds ? `${fmtDuration(lastNightSleepSeconds)} asleep · ${readingWindow(lastNight.started_at, lastNight.ended_at)}` : metrics.length || lastNight ? "We have health readings, but need a valid sleep duration to show recovery trends." : "Connect Apple Health or import a Health Auto Export file to see recovery trends."}</p></div>
    {(lastNight || latestWorkout) && <div className="grid grid-cols-2 gap-2">{lastNight && <SleepSummaryCard session={lastNight} />}{latestWorkout && <WorkoutSummaryCard workout={latestWorkout} />}</div>}
    <div className="grid grid-cols-2 gap-2"><MetricCard icon={HeartPulse} label="Resting HR" value={latestRhr ? `${Math.round(latestRhr.value)} bpm` : "—"} metric={readingMeta(latestRhr)} source={latestRhr?.provider} /><MetricCard icon={Activity} label="HRV" value={latestHrv ? `${latestHrv.value.toFixed(1)} ms` : "—"} metric={readingMeta(latestHrv)} source={latestHrv?.provider} /><MetricCard icon={Activity} label="Steps" value={latestSteps ? Math.round(latestSteps.value).toLocaleString("en-IN") : "—"} metric={readingMeta(latestSteps)} source={latestSteps?.provider} /><MetricCard icon={Scale} label="Weight" value={latestWeight ? `${latestWeight.value.toFixed(1)} kg` : "—"} metric={readingMeta(latestWeight)} source={latestWeight?.provider} /></div>
    <RecentReadings metrics={metrics} sleep={sleep} />
    <WorkoutHistory workouts={workouts} />
    <div className="rounded-xl border border-border bg-card p-3"><div className="flex items-center justify-between"><p className="text-[11px] font-bold text-foreground">Manual weight</p><p className="text-[10px] text-muted">{weightTrend.length ? `${weightTrend.length} measurements` : "No measurements"}</p></div><div className="mt-2 flex gap-2"><input value={weight} onChange={(e) => setWeight(e.target.value)} type="number" min="20" max="500" step="0.1" placeholder="kg" className="min-w-0 flex-1 rounded-lg border border-border bg-background px-2.5 py-2 text-xs" /><button onClick={saveWeight} disabled={!weight} className="rounded-lg bg-foreground px-3 py-2 text-[11px] font-bold text-white disabled:opacity-40">Save</button></div><p className="mt-2 text-[10px] text-muted">Adds a measurement and updates profile weight. It does not recalculate nutrition goals.</p></div>
    {message && <p className="text-[10px] text-accent-dim flex items-center gap-1"><Check className="h-3 w-3" />{message}</p>}<button onClick={() => void load()} className="flex items-center gap-1 text-[10px] font-semibold text-muted hover:text-foreground"><RefreshCw className="h-3 w-3" />Refresh health data</button>
  </div>;
}

function SyncMethodChooser({ method, setMethod, connected, token, generate, busy, uploadRef, uploadExport }: { method: SyncMethod; setMethod: (method: SyncMethod) => void; connected: boolean; token: string; generate: () => Promise<void>; busy: boolean; uploadRef: React.RefObject<HTMLInputElement | null>; uploadExport: (file: File) => Promise<void> }) {
  return <div className="rounded-2xl border border-border bg-card p-4 space-y-3"><p className="text-xs font-extrabold text-foreground">Choose how to sync</p><div className="grid grid-cols-2 gap-2"><button onClick={() => setMethod("premium")} className={`rounded-xl border p-3 text-left ${method === "premium" ? "border-accent bg-accent-light/40" : "border-border"}`}><p className="text-[11px] font-bold text-foreground">Automatic</p><p className="mt-1 text-[10px] text-muted">Set it up once with Premium</p></button><button onClick={() => setMethod("basic")} className={`rounded-xl border p-3 text-left ${method === "basic" ? "border-accent bg-accent-light/40" : "border-border"}`}><p className="text-[11px] font-bold text-foreground">Free upload</p><p className="mt-1 text-[10px] text-muted">Upload a JSON export anytime</p></button></div>{method === "premium" ? <div className="rounded-xl bg-background border border-border p-3 text-[10px] text-muted space-y-2"><p className="font-bold text-foreground">Automatic sync with Premium</p><p>Connect Health Auto Export Premium once and SnackOverflow will receive your workouts, sleep, and health metrics automatically.</p><a href="/connected-health/automatic-sync" className="inline-flex items-center gap-1 font-bold text-accent-dim">See the setup guide <ExternalLink className="h-3 w-3" /></a>{!token && <p>Your connection token is already saved. Revoke it above and generate a new one only if you need to replace it.</p>}</div> : <div className="rounded-xl bg-background border border-border p-3 text-[10px] text-muted space-y-2"><p className="font-bold text-foreground">Free sync</p><p>Export JSON from Health Auto Export Basic, then upload it here. Your SnackOverflow login keeps the upload secure; no token is needed.</p><input ref={uploadRef} type="file" accept=".json,application/json" className="hidden" onChange={(e) => { const file = e.target.files?.[0]; if (file) void uploadExport(file); e.currentTarget.value = ""; }} /><button onClick={() => uploadRef.current?.click()} disabled={busy || !connected} className="inline-flex items-center gap-1 rounded-lg bg-foreground px-3 py-2 text-[10px] font-bold text-white disabled:opacity-40"><FileUp className="h-3 w-3" />{connected ? "Upload JSON export" : "Create connection first"}</button><a href="/shortcuts/snackoverflow-health-sync.shortcut" download className="ml-2 text-[10px] font-bold text-accent-dim">Use iPhone Shortcut</a></div>}</div>;
}

function WorkoutHistory({ workouts }: { workouts: Workout[] }) { const [expanded, setExpanded] = useState<string | null>(null); return <details className="rounded-2xl border border-border bg-card overflow-hidden"><summary className="flex cursor-pointer list-none items-center justify-between p-4"><div><p className="text-xs font-extrabold text-foreground">Recent workouts</p><p className="text-[10px] text-muted">{workouts.length ? `${workouts.length} saved · tap to view details` : "No workouts imported yet"}</p></div><ChevronDown className="h-4 w-4 text-muted" /></summary>{workouts.length > 0 && <div className="border-t border-border p-4 pt-3"><p className="mb-2 text-[10px] text-muted">Showing the latest {Math.min(workouts.length, 10)} workouts. Tap one for calories, distance, and heart rate.</p><div className="space-y-2">{workouts.slice(0, 10).map((workout, index) => { const key = `${workout.started_at}-${index}`; const isOpen = expanded === key; return <div key={key} className="rounded-xl bg-background border border-border overflow-hidden"><button onClick={() => setExpanded(isOpen ? null : key)} className="w-full p-3 text-left"><div className="flex items-center justify-between gap-2"><p className="text-[11px] font-bold text-foreground">{workout.workout_type}</p><span className="flex items-center gap-1 text-[10px] text-muted">{fmtDate(workout.started_at)} {isOpen ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}</span></div><p className="mt-1 text-[10px] text-muted">{fmtDuration(workout.duration_seconds)}{workout.energy_kcal !== null ? ` · ${Math.round(workout.energy_kcal)} kcal` : ""}{workout.distance_km !== null ? ` · ${workout.distance_km.toFixed(1)} km` : ""}{workout.heart_rate_avg_bpm !== null ? ` · avg HR ${Math.round(workout.heart_rate_avg_bpm)} bpm` : ""}</p></button>{isOpen && <div className="border-t border-border px-3 pb-3 pt-2"><div className="grid grid-cols-2 gap-2 text-[10px]"><Detail icon={Timer} label="Duration" value={fmtDuration(workout.duration_seconds)} /><Detail icon={Flame} label="Calories burned" value={workout.energy_kcal !== null ? `${Math.round(workout.energy_kcal)} kcal` : "—"} /><Detail icon={MapPin} label="Distance" value={workout.distance_km !== null ? `${workout.distance_km.toFixed(1)} km` : "—"} /><Detail icon={HeartPulse} label="Heart rate" value={workout.heart_rate_avg_bpm !== null ? `${Math.round(workout.heart_rate_avg_bpm)} bpm avg` : "—"} /></div><p className="mt-2 text-[10px] text-muted">{new Date(workout.started_at).toLocaleTimeString("en-IN", { hour: "numeric", minute: "2-digit" })} – {new Date(workout.ended_at).toLocaleTimeString("en-IN", { hour: "numeric", minute: "2-digit" })}{workout.heart_rate_min_bpm != null || workout.heart_rate_max_bpm != null ? ` · range ${workout.heart_rate_min_bpm ?? "—"}–${workout.heart_rate_max_bpm ?? "—"} bpm` : ""}</p></div>}</div>; })}</div></div>}</details>; }
function Detail({ icon: Icon, label, value }: { icon: typeof Activity; label: string; value: string }) { return <div className="rounded-lg border border-border p-2"><div className="flex items-center gap-1 text-muted"><Icon className="h-3 w-3" />{label}</div><p className="mt-1 font-bold text-foreground">{value}</p></div>; }
function Mini({ icon: Icon, label, value, detail }: { icon: typeof Activity; label: string; value: string; detail?: string }) { return <div className="rounded-xl border border-border bg-card p-3"><Icon className="h-3.5 w-3.5 text-accent" /><p className="mt-1 text-[10px] text-muted">{label}</p><p className="text-sm font-extrabold text-foreground">{value}</p>{detail && <p className="text-[9px] text-muted">{detail}</p>}</div>; }
function MiniText({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] text-muted">{label}</p><p className="text-[11px] font-bold text-foreground">{value}</p></div>; }
function sourceLabel(provider?: string | null) { if (!provider) return "Source unavailable"; if (provider === "manual_upload") return "Health Auto Export"; if (provider === "apple_shortcut") return "Shortcut"; if (provider === "manual") return "Manual"; return "Apple Health"; }
function readingMeta(metric?: Metric) { return metric ? fmtDateTime(metric.recorded_at) : "No reading yet"; }
function fmtDateTime(iso: string) { return new Date(iso).toLocaleString("en-IN", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" }); }
function readingWindow(start: string, end: string) { return `${new Date(start).toLocaleTimeString("en-IN", { hour: "numeric", minute: "2-digit" })} – ${new Date(end).toLocaleTimeString("en-IN", { hour: "numeric", minute: "2-digit" })}`; }
function MetricCard({ icon: Icon, label, value, metric, source }: { icon: typeof Activity; label: string; value: string; metric: string; source?: string }) { return <div className="rounded-xl border border-border bg-card p-3"><Icon className="h-3.5 w-3.5 text-accent" /><p className="mt-1 text-[10px] text-muted">{label}</p><p className="text-sm font-extrabold text-foreground">{value}</p><p className="mt-1 text-[9px] leading-tight text-muted">{metric}</p>{source && <p className="text-[9px] text-accent-dim">{sourceLabel(source)}</p>}</div>; }
function SleepSummaryCard({ session }: { session: Sleep }) { const total = effectiveSleepSeconds(session) ?? 0; const stages = [{ label: "Core", value: session.core_seconds ?? 0, color: "#71c979" }, { label: "Deep", value: session.deep_seconds ?? 0, color: "#3c8553" }, { label: "REM", value: session.rem_seconds ?? 0, color: "#9ad89a" }]; const circumference = 276.46; let offset = 0; return <div className="rounded-xl border border-border bg-card p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-[10px] font-bold text-muted">Sleep</p><p className="mt-0.5 text-[13px] font-extrabold text-foreground">{fmtDate(session.started_at)}</p><p className="mt-0.5 text-[9px] text-accent-dim">{sourceLabel(session.provider)}</p></div><span className="rounded-full bg-accent-light/60 px-2 py-1 text-[9px] font-bold text-accent-dim">{total >= 7 * 3600 ? "Good night" : "Recovery"}</span></div><div className="mt-3 flex flex-col items-center"><div className="relative h-[94px] w-[94px] -rotate-90"><svg viewBox="0 0 100 100" className="h-full w-full"><circle cx="50" cy="50" r="44" fill="none" stroke="currentColor" className="text-border/60" strokeWidth="9" />{stages.map((stage) => { const length = total > 0 ? (stage.value / total) * circumference : 0; const currentOffset = offset; offset += length; return <circle key={stage.label} cx="50" cy="50" r="44" fill="none" stroke={stage.color} strokeWidth="9" strokeDasharray={`${length} ${circumference - length}`} strokeDashoffset={-currentOffset} />; })}</svg><div className="absolute inset-0 flex rotate-90 flex-col items-center justify-center"><p className="text-[15px] font-extrabold leading-none text-foreground">{fmtDuration(total)}</p><p className="mt-1 text-[8px] font-bold text-muted">asleep</p></div></div><div className="mt-3 w-full space-y-1.5">{stages.map((stage) => <div key={stage.label} className="flex items-center justify-between text-[9px]"><span className="flex items-center gap-1.5 text-muted"><span className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: stage.color }} />{stage.label}</span><strong className="text-foreground">{fmtDuration(stage.value)}</strong></div>)}</div></div><p className="mt-3 border-t border-border pt-2 text-[9px] text-muted">{readingWindow(session.started_at, session.ended_at)}</p></div>; }
function WorkoutSummaryCard({ workout }: { workout: Workout }) { const duration = workout.duration_seconds ?? 0; const progress = Math.min(1, duration / 3600); const circumference = 276.46; return <div className="rounded-xl border border-border bg-card p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-[10px] font-bold text-muted">Workout</p><p className="mt-0.5 truncate text-[13px] font-extrabold text-foreground">{workout.workout_type}</p><p className="mt-0.5 text-[9px] text-accent-dim">{sourceLabel(workout.provider)}</p></div><span className="rounded-full bg-accent-light/60 px-2 py-1 text-[9px] font-bold text-accent-dim">Latest</span></div><div className="mt-3 flex justify-center"><div className="relative h-[94px] w-[94px] -rotate-90"><svg viewBox="0 0 100 100" className="h-full w-full"><circle cx="50" cy="50" r="44" fill="none" stroke="currentColor" className="text-border/60" strokeWidth="9" /><circle cx="50" cy="50" r="44" fill="none" stroke="currentColor" className="text-accent" strokeWidth="9" strokeLinecap="round" strokeDasharray={`${progress * circumference} ${circumference - progress * circumference}`} /></svg><div className="absolute inset-0 flex rotate-90 flex-col items-center justify-center"><p className="text-[15px] font-extrabold leading-none text-foreground">{fmtDuration(duration)}</p><p className="mt-1 text-[8px] font-bold text-muted">moving</p></div></div></div><div className="mt-3 space-y-1.5 text-[9px]"><div className="flex justify-between"><span className="text-muted">Energy</span><strong className="text-foreground">{workout.energy_kcal !== null ? `${Math.round(workout.energy_kcal)} kcal` : "—"}</strong></div><div className="flex justify-between"><span className="text-muted">Avg HR</span><strong className="text-foreground">{workout.heart_rate_avg_bpm !== null ? `${Math.round(workout.heart_rate_avg_bpm)} bpm` : "—"}</strong></div></div><p className="mt-3 border-t border-border pt-2 text-[9px] text-muted">{fmtDate(workout.started_at)} · {new Date(workout.started_at).toLocaleTimeString("en-IN", { hour: "numeric", minute: "2-digit" })}</p></div>; }
function RecentReadings({ metrics, sleep }: { metrics: Metric[]; sleep: Sleep[] }) { const rows = [...sleep.map((session) => ({ at: session.ended_at, label: "Sleep", meta: `${session.sleep_date} · ${readingWindow(session.started_at, session.ended_at)} · ${sourceLabel(session.provider)}`, value: effectiveSleepSeconds(session) != null ? fmtDuration(effectiveSleepSeconds(session)) : "Incomplete" })), ...metrics.map((metric) => ({ at: metric.recorded_at, label: metric.metric_type.replaceAll("_", " "), meta: `${fmtDateTime(metric.recorded_at)} · ${sourceLabel(metric.provider)}`, value: `${metric.value.toLocaleString("en-IN", { maximumFractionDigits: 1 })} ${metric.unit}` }))].sort((a, b) => new Date(b.at).getTime() - new Date(a.at).getTime()).slice(0, 8); return <div className="rounded-2xl border border-border bg-card overflow-hidden"><div className="flex items-center justify-between p-4"><div><p className="text-xs font-extrabold capitalize text-foreground">Recent readings</p><p className="text-[10px] text-muted">Latest {rows.length || "health"} imported records</p></div><span className="text-[10px] text-muted">{metrics.length + sleep.length} total</span></div>{rows.length === 0 ? <p className="border-t border-border px-4 py-3 text-[10px] text-muted">No readings imported yet.</p> : <div className="divide-y divide-border border-t border-border px-4">{rows.map((row, index) => <div key={`${row.label}-${row.at}-${index}`} className="flex items-center justify-between gap-3 py-2.5"><div><p className="text-[10px] font-bold capitalize text-foreground">{row.label}</p><p className="text-[9px] text-muted">{row.meta}</p></div><p className="shrink-0 text-[11px] font-extrabold capitalize text-foreground">{row.value}</p></div>)}</div>}</div>; }
